# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65ca3346ccc1a508992a6810040627bf66b54756ae94811ea171a8ab106599a1033b11c0c50d9de8b376043fac736f3be1b106b7b9a32ec5339118dc79a51dc3

test:
  secret_key_base: ca12482ee0b9eb37e493e93ec2196bdd1d7267482bb9f7013f53b2dc1cc379958b39aeb93446fdda2d89f1a1eee29ef4b7e8be7c32b9bd5dba7a49eedd7d879e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
